# Generated by Django 4.0.1 on 2022-01-30 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pella3', '0002_internship_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='owner',
        ),
    ]
