# Generated by Django 4.0.1 on 2022-01-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pella', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referrals',
            new_name='Referral',
        ),
    ]
