# Generated by Django 4.0.1 on 2022-01-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pella', '0002_rename_referrals_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='images/'),
        ),
    ]
